sudo: required
services:
  - docker

before_install:
  - docker build -t ishjolly/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ishjolly/react-test npm test -- --coverage

after_success: 
  - docker build -t ishjolly/multi-client ./client
  - docker build -t ishjolly/multi-nginx ./nginx
  - docker build -t ishjolly/multi-server ./server
  - docker build -t ishjolly/multi-worker ./worker
  # Log in to the docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ishjolly/multi-client
  - docker push ishjolly/multi-nginx
  - docker push ishjolly/multi-server
  - docker push ishjolly/multi-worker